services:
    postgres:
        image: postgres:latest
        restart: unless-stopped
        container_name: postgres
        environment:
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_USER}
        ports:
            - "127.0.0.1:5432:5432"
        expose:
            - 5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        # healthcheck:
        #     test: ["CMD-SHELL", "pg_isready -U postgres"]
        #     interval: 10s
        #     timeout: 5s
        #     retries: 5
    redis:
        restart: unless-stopped
        image: redis
        ports:
            - "127.0.0.1:6380:6379"
        expose:
            - 6380
        volumes:
            - redis_data:/data
    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4:latest
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "5050:80"
        volumes:
            - pgadmin_data:/var/lib/pgadmin
    pdf_api:
        image: pdf_api:latest
        restart: unless-stopped
        ports:
            - "127.0.0.1:5000:3000"
volumes:
    postgres_data:
    redis_data:
    pgadmin_data:
    web_data:
