-- AlterTable
ALTER TABLE "users" ALTER COLUMN "middle_name" SET DEFAULT '',
ALTER COLUMN "title" SET DEFAULT '',
ALTER COLUMN "affiliation" SET DEFAULT '',
ALTER COLUMN "web_page" SET DEFAULT '',
ALTER COLUMN "address_line_1" SET DEFAULT '',
ALTER COLUMN "address_line_2" SET DEFAULT '',
ALTER COLUMN "orcid_id" SET DEFAULT '',
ALTER COLUMN "city" SET DEFAULT '',
ALTER COLUMN "state" SET DEFAULT '',
ALTER COLUMN "country" SET DEFAULT '';
